# Generated by Django 2.2 on 2020-06-05 11:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20200605_0301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='statutCompte',
        ),
        migrations.AddField(
            model_name='profile',
            name='besoin',
            field=models.BooleanField(default=False, verbose_name='Besoin'),
        ),
        migrations.AddField(
            model_name='profile',
            name='montant',
            field=models.IntegerField(blank=True, null=True, verbose_name='Montant du besoin'),
        ),
        migrations.AlterField(
            model_name='souscriptions',
            name='dateDexpiration',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 5, 11, 52, 17, 891154), verbose_name='Expire le'),
        ),
    ]
