# Generated by Django 2.2 on 2020-06-05 12:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20200605_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apporteraide',
            name='recepteur',
            field=models.ForeignKey(blank=True, limit_choices_to={'besoin': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Récepteur', to='profiles.Profile', verbose_name='Récepteur'),
        ),
        migrations.AlterField(
            model_name='souscriptions',
            name='dateDexpiration',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 5, 12, 48, 9, 988230), verbose_name='Expire le'),
        ),
        migrations.AlterField(
            model_name='souscriptions',
            name='moyenDePaiment',
            field=models.CharField(blank=True, choices=[('Mobile money', 'Mobile money'), ('Paypal', 'Paypal')], default='PayPal', max_length=20, verbose_name='Moyen de paiement'),
        ),
        migrations.AlterField(
            model_name='souscriptions',
            name='statutCompte',
            field=models.BooleanField(default=False, verbose_name='Compte actif'),
        ),
    ]
