# Generated by Django 2.2 on 2020-06-05 13:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20200605_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='besoinsemis',
            name='idAide',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Ref aide'),
        ),
        migrations.AlterField(
            model_name='souscriptions',
            name='dateDexpiration',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 5, 13, 37, 7, 82632), verbose_name='Expire le'),
        ),
        migrations.AlterField(
            model_name='souscriptions',
            name='moyenDePaiment',
            field=models.CharField(blank=True, choices=[('Mobile money', 'Mobile money'), ('Paypal', 'Paypal')], default='Paypal', max_length=20, verbose_name='Moyen de paiement'),
        ),
    ]
