# Generated by Django 2.2 on 2020-06-05 17:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20200605_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='besoinsemis',
            name='paye',
            field=models.IntegerField(blank=True, null=True, verbose_name='Payé'),
        ),
        migrations.AddField(
            model_name='besoinsemis',
            name='restant',
            field=models.IntegerField(blank=True, null=True, verbose_name='Restant'),
        ),
        migrations.AlterField(
            model_name='apporteraide',
            name='montantApporte',
            field=models.IntegerField(blank=True, choices=[(25000, '25.000 XOF'), (50000, '50.000 XOF'), (100000, '100.000 XOF'), (200000, '200.000 XOF'), (250000, '250.000 XOF'), (400000, '400.000 XOF'), (500000, '500.000 XOF')], null=True, verbose_name='Montant Apporté'),
        ),
        migrations.AlterField(
            model_name='souscriptions',
            name='dateDexpiration',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 5, 17, 36, 46, 544549), verbose_name='Expire le'),
        ),
    ]
