# Generated by Django 2.2 on 2020-06-07 00:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20200605_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pays',
            field=models.CharField(blank=True, choices=[('South Africa', 'South Africa'), ('Algérie', 'Algérie'), ('Allemagne', 'Allemagne'), ('Australia', 'Australia'), ('Angola', 'Angola'), ('Belgique', 'Belgique'), ('Benin', 'Benin'), ('Botswana', 'Botswana'), ('Brazilia', 'Brazilia'), ('Burkina Faso', 'Burkina Faso'), ('Canada', 'Canada'), ('Cameroun', 'Cameroun'), ('RD Congo', 'RD Congo'), ("Côte d'Ivoire", "Côte d'Ivoire"), ('Damemark', 'Damemark'), ('Finland', 'Finland'), ('France', 'France'), ('Gabon', 'Gabon'), ('Gambie', 'Gambie'), ('Ghana', 'Ghana'), ('Guinéé', 'Guinéé'), ('Israel', 'Israel'), ('Mali', 'Mali'), ('Maroc', 'Maroc'), ('Nigeria', 'Nigeria'), ('Niger', 'Niger'), ('Togo', 'Togo'), ('Tunisia', 'Tunisia'), ('USA', 'USA')], default='South Africa', max_length=25, verbose_name='Pays'),
        ),
        migrations.AlterField(
            model_name='souscriptions',
            name='dateDexpiration',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 7, 0, 16, 7, 362572), verbose_name='Expire le'),
        ),
        migrations.CreateModel(
            name='Benefices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montantBenefice', models.IntegerField(blank=True, null=True, verbose_name='Montant du bénéfice')),
                ('dateBenefice', models.DateTimeField(auto_now=True, verbose_name='date')),
                ('utilisateur', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile', verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'benefices',
                'verbose_name_plural': 'benefices',
                'db_table': 'benefices',
                'managed': True,
            },
        ),
    ]
