# Generated by Django 2.2 on 2020-06-13 23:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20200607_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='apporteraide',
            name='dateLimiteEnvoi',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date butoire envoi'),
        ),
        migrations.AddField(
            model_name='apporteraide',
            name='dateLimiteReception',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date butoire reception'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='contact',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nomComplet',
            field=models.CharField(blank=True, default='', max_length=100, null=True, unique=True, verbose_name='Nom et Prenoms'),
        ),
        migrations.AlterField(
            model_name='souscriptions',
            name='dateDexpiration',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 13, 23, 2, 22, 708114), verbose_name='Expire le'),
        ),
    ]
