# Generated by Django 2.2 on 2020-06-14 17:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_auto_20200614_1653'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Informations',
        ),
        migrations.AlterField(
            model_name='souscriptions',
            name='dateDexpiration',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 14, 17, 2, 1, 561543), verbose_name='Expire le'),
        ),
    ]
