# Generated by Django 2.2 on 2020-06-14 17:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_auto_20200614_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='souscriptions',
            name='dateDexpiration',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 14, 17, 17, 30, 789881), verbose_name='Expire le'),
        ),
    ]
